/**
 * Environment variable declarations for secrets.
 * Secrets are not auto-generated by wrangler types, so we declare them here.
 *
 * To add secrets:
 * - Production: `wrangler secret put GOOGLE_MAPS_API_KEY`
 * - Local development: Add to `.dev.vars` file
 */
declare namespace Cloudflare {
  interface Env {
    /**
     * Google Maps Geocoding API key
     * @see https://developers.google.com/maps/documentation/geocoding/overview
     */
    GOOGLE_MAPS_API_KEY: string;
  }
}
